#![allow(
    non_camel_case_types,
    unused,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::double_parens,
    non_snake_case,
    clippy::too_many_arguments
)]
// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.73.0.

use crate::api_vup::*;
use core::panic::UnwindSafe;
use flutter_rust_bridge::*;
use std::ffi::c_void;
use std::sync::Arc;

// Section: imports

// Section: wire functions

fn wire_encrypt_file_xchacha20_impl(
    port_: MessagePort,
    input_file_path: impl Wire2Api<String> + UnwindSafe,
    output_file_path: impl Wire2Api<String> + UnwindSafe,
    padding: impl Wire2Api<usize> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "encrypt_file_xchacha20",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_input_file_path = input_file_path.wire2api();
            let api_output_file_path = output_file_path.wire2api();
            let api_padding = padding.wire2api();
            move |task_callback| {
                encrypt_file_xchacha20(api_input_file_path, api_output_file_path, api_padding)
            }
        },
    )
}
fn wire_decrypt_file_xchacha20_impl(
    port_: MessagePort,
    input_file_path: impl Wire2Api<String> + UnwindSafe,
    output_file_path: impl Wire2Api<String> + UnwindSafe,
    key: impl Wire2Api<Vec<u8>> + UnwindSafe,
    padding: impl Wire2Api<usize> + UnwindSafe,
    last_chunk_index: impl Wire2Api<u32> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "decrypt_file_xchacha20",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_input_file_path = input_file_path.wire2api();
            let api_output_file_path = output_file_path.wire2api();
            let api_key = key.wire2api();
            let api_padding = padding.wire2api();
            let api_last_chunk_index = last_chunk_index.wire2api();
            move |task_callback| {
                decrypt_file_xchacha20(
                    api_input_file_path,
                    api_output_file_path,
                    api_key,
                    api_padding,
                    api_last_chunk_index,
                )
            }
        },
    )
}
fn wire_generate_thumbnail_for_image_file_impl(
    port_: MessagePort,
    image_type: impl Wire2Api<String> + UnwindSafe,
    path: impl Wire2Api<String> + UnwindSafe,
    exif_image_orientation: impl Wire2Api<u8> + UnwindSafe,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap(
        WrapInfo {
            debug_name: "generate_thumbnail_for_image_file",
            port: Some(port_),
            mode: FfiCallMode::Normal,
        },
        move || {
            let api_image_type = image_type.wire2api();
            let api_path = path.wire2api();
            let api_exif_image_orientation = exif_image_orientation.wire2api();
            move |task_callback| {
                generate_thumbnail_for_image_file(
                    api_image_type,
                    api_path,
                    api_exif_image_orientation,
                )
            }
        },
    )
}
// Section: wrapper structs

// Section: static checks

// Section: allocate functions

// Section: related functions

// Section: impl Wire2Api

pub trait Wire2Api<T> {
    fn wire2api(self) -> T;
}

impl<T, S> Wire2Api<Option<T>> for *mut S
where
    *mut S: Wire2Api<T>,
{
    fn wire2api(self) -> Option<T> {
        (!self.is_null()).then(|| self.wire2api())
    }
}

impl Wire2Api<u32> for u32 {
    fn wire2api(self) -> u32 {
        self
    }
}
impl Wire2Api<u8> for u8 {
    fn wire2api(self) -> u8 {
        self
    }
}

impl Wire2Api<usize> for usize {
    fn wire2api(self) -> usize {
        self
    }
}
// Section: impl IntoDart

impl support::IntoDart for ThumbnailResponse {
    fn into_dart(self) -> support::DartAbi {
        vec![
            self.bytes.into_dart(),
            self.thumbhash_bytes.into_dart(),
            self.width.into_dart(),
            self.height.into_dart(),
        ]
        .into_dart()
    }
}
impl support::IntoDartExceptPrimitive for ThumbnailResponse {}

// Section: executor

support::lazy_static! {
    pub static ref FLUTTER_RUST_BRIDGE_HANDLER: support::DefaultHandler = Default::default();
}

#[cfg(not(target_family = "wasm"))]
#[path = "bridge_generated_vup.io.rs"]
mod io;
#[cfg(not(target_family = "wasm"))]
pub use io::*;
